/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/root'
import { Route as LoginImport } from './routes/login'
import { Route as PrivateImport } from './routes/private'
import { Route as IndexImport } from './routes/index'
import { Route as PrivateSettingsImport } from './routes/private/settings'
import { Route as PrivateProjectImport } from './routes/private/project'
import { Route as PrivateProfileImport } from './routes/private/profile'
import { Route as PrivateMessengerImport } from './routes/private/messenger'
import { Route as PrivateHomeImport } from './routes/private/home'
import { Route as PrivateSettingsIndexImport } from './routes/private/settings/index'
import { Route as PrivateProjectIndexImport } from './routes/private/project/index'
import { Route as PrivateSettingsOperationImport } from './routes/private/settings/operation'
import { Route as PrivateSettingsGeneralImport } from './routes/private/settings/general'
import { Route as PrivateProjectProjectIdImport } from './routes/private/project/$projectId'
import { Route as PrivateSettingsOperationIndexImport } from './routes/private/settings/operation/index'
import { Route as PrivateSettingsGeneralIndexImport } from './routes/private/settings/general/index'
import { Route as PrivateProjectProjectIdIndexImport } from './routes/private/project/$projectId/index'
import { Route as PrivateSettingsOperationProcessListImport } from './routes/private/settings/operation/process/list'
import { Route as PrivateSettingsOperationObjectsListImport } from './routes/private/settings/operation/objects/list'
import { Route as PrivateSettingsGeneralSuppliersListImport } from './routes/private/settings/general/suppliers/list'
import { Route as PrivateSettingsGeneralMaterialsListImport } from './routes/private/settings/general/materials/list'
import { Route as PrivateSettingsGeneralEmployeesListImport } from './routes/private/settings/general/employees/list'
import { Route as PrivateSettingsGeneralDepartmentsListImport } from './routes/private/settings/general/departments/list'
import { Route as PrivateSettingsGeneralCustomersListImport } from './routes/private/settings/general/customers/list'
import { Route as PrivateProjectProjectIdSettingsImport } from './routes/private/project/$projectId/settings'
import { Route as PrivateProjectProjectIdIssuesImport } from './routes/private/project/$projectId/issues'
import { Route as PrivateProjectProjectIdContractImport } from './routes/private/project/$projectId/contract'
import { Route as PrivateProjectProjectIdIssuesIndexImport } from './routes/private/project/$projectId/issues/index'
import { Route as PrivateProjectProjectIdContractIndexImport } from './routes/private/project/$projectId/contract/index'
import { Route as PrivateSettingsOperationProcessNewImport } from './routes/private/settings/operation/process/new'
import { Route as PrivateSettingsOperationObjectsNewImport } from './routes/private/settings/operation/objects/new'
import { Route as PrivateSettingsGeneralSuppliersNewImport } from './routes/private/settings/general/suppliers/new'
import { Route as PrivateSettingsGeneralMaterialsNewImport } from './routes/private/settings/general/materials/new'
import { Route as PrivateSettingsGeneralEmployeesNewImport } from './routes/private/settings/general/employees/new'
import { Route as PrivateSettingsGeneralDepartmentsNewImport } from './routes/private/settings/general/departments/new'
import { Route as PrivateSettingsGeneralCustomersNewImport } from './routes/private/settings/general/customers/new'
import { Route as PrivateProjectProjectIdIssuesRequestImport } from './routes/private/project/$projectId/issues/request'
import { Route as PrivateProjectProjectIdIssuesPriceImport } from './routes/private/project/$projectId/issues/price'
import { Route as PrivateProjectProjectIdIssuesMeImport } from './routes/private/project/$projectId/issues/me'
import { Route as PrivateProjectProjectIdContractMonitoringImport } from './routes/private/project/$projectId/contract/monitoring'
import { Route as PrivateProjectProjectIdContractInputImport } from './routes/private/project/$projectId/contract/input'
import { Route as PrivateProjectProjectIdIssuesRequestIndexImport } from './routes/private/project/$projectId/issues/request/index'
import { Route as PrivateProjectProjectIdIssuesPriceIndexImport } from './routes/private/project/$projectId/issues/price/index'
import { Route as PrivateProjectProjectIdIssuesMeIndexImport } from './routes/private/project/$projectId/issues/me/index'
import { Route as PrivateSettingsOperationProcessEditImport } from './routes/private/settings/operation/process/edit'
import { Route as PrivateSettingsOperationObjectsEditImport } from './routes/private/settings/operation/objects/edit'
import { Route as PrivateSettingsGeneralSuppliersEditImport } from './routes/private/settings/general/suppliers/edit'
import { Route as PrivateSettingsGeneralMaterialsEditImport } from './routes/private/settings/general/materials/edit'
import { Route as PrivateSettingsGeneralEmployeesEditImport } from './routes/private/settings/general/employees/edit'
import { Route as PrivateSettingsGeneralDepartmentsEditImport } from './routes/private/settings/general/departments/edit'
import { Route as PrivateSettingsGeneralCustomersEditImport } from './routes/private/settings/general/customers/edit'
import { Route as PrivateProjectProjectIdIssuesRequestIssueIdImport } from './routes/private/project/$projectId/issues/request/$issueId'
import { Route as PrivateProjectProjectIdIssuesPriceIssueIdImport } from './routes/private/project/$projectId/issues/price/$issueId'
import { Route as PrivateProjectProjectIdIssuesMeIssueIdImport } from './routes/private/project/$projectId/issues/me/$issueId'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PrivateSettingsRoute = PrivateSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProjectRoute = PrivateProjectImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateProfileRoute = PrivateProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateMessengerRoute = PrivateMessengerImport.update({
  id: '/messenger',
  path: '/messenger',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateHomeRoute = PrivateHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateSettingsIndexRoute = PrivateSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

const PrivateProjectIndexRoute = PrivateProjectIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateProjectRoute,
} as any)

const PrivateSettingsOperationRoute = PrivateSettingsOperationImport.update({
  id: '/operation',
  path: '/operation',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

const PrivateSettingsGeneralRoute = PrivateSettingsGeneralImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => PrivateSettingsRoute,
} as any)

const PrivateProjectProjectIdRoute = PrivateProjectProjectIdImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => PrivateProjectRoute,
} as any)

const PrivateSettingsOperationIndexRoute =
  PrivateSettingsOperationIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateSettingsOperationRoute,
  } as any)

const PrivateSettingsGeneralIndexRoute =
  PrivateSettingsGeneralIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateSettingsGeneralRoute,
  } as any)

const PrivateProjectProjectIdIndexRoute =
  PrivateProjectProjectIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProjectProjectIdRoute,
  } as any)

const PrivateSettingsOperationProcessListRoute =
  PrivateSettingsOperationProcessListImport.update({
    id: '/process',
    path: '/process',
    getParentRoute: () => PrivateSettingsOperationRoute,
  } as any)

const PrivateSettingsOperationObjectsListRoute =
  PrivateSettingsOperationObjectsListImport.update({
    id: '/objects',
    path: '/objects',
    getParentRoute: () => PrivateSettingsOperationRoute,
  } as any)

const PrivateSettingsGeneralSuppliersListRoute =
  PrivateSettingsGeneralSuppliersListImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => PrivateSettingsGeneralRoute,
  } as any)

const PrivateSettingsGeneralMaterialsListRoute =
  PrivateSettingsGeneralMaterialsListImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => PrivateSettingsGeneralRoute,
  } as any)

const PrivateSettingsGeneralEmployeesListRoute =
  PrivateSettingsGeneralEmployeesListImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => PrivateSettingsGeneralRoute,
  } as any)

const PrivateSettingsGeneralDepartmentsListRoute =
  PrivateSettingsGeneralDepartmentsListImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => PrivateSettingsGeneralRoute,
  } as any)

const PrivateSettingsGeneralCustomersListRoute =
  PrivateSettingsGeneralCustomersListImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => PrivateSettingsGeneralRoute,
  } as any)

const PrivateProjectProjectIdSettingsRoute =
  PrivateProjectProjectIdSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PrivateProjectProjectIdRoute,
  } as any)

const PrivateProjectProjectIdIssuesRoute =
  PrivateProjectProjectIdIssuesImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => PrivateProjectProjectIdRoute,
  } as any)

const PrivateProjectProjectIdContractRoute =
  PrivateProjectProjectIdContractImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => PrivateProjectProjectIdRoute,
  } as any)

const PrivateProjectProjectIdIssuesIndexRoute =
  PrivateProjectProjectIdIssuesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProjectProjectIdIssuesRoute,
  } as any)

const PrivateProjectProjectIdContractIndexRoute =
  PrivateProjectProjectIdContractIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProjectProjectIdContractRoute,
  } as any)

const PrivateSettingsOperationProcessNewRoute =
  PrivateSettingsOperationProcessNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsOperationProcessListRoute,
  } as any)

const PrivateSettingsOperationObjectsNewRoute =
  PrivateSettingsOperationObjectsNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsOperationObjectsListRoute,
  } as any)

const PrivateSettingsGeneralSuppliersNewRoute =
  PrivateSettingsGeneralSuppliersNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsGeneralSuppliersListRoute,
  } as any)

const PrivateSettingsGeneralMaterialsNewRoute =
  PrivateSettingsGeneralMaterialsNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsGeneralMaterialsListRoute,
  } as any)

const PrivateSettingsGeneralEmployeesNewRoute =
  PrivateSettingsGeneralEmployeesNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsGeneralEmployeesListRoute,
  } as any)

const PrivateSettingsGeneralDepartmentsNewRoute =
  PrivateSettingsGeneralDepartmentsNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsGeneralDepartmentsListRoute,
  } as any)

const PrivateSettingsGeneralCustomersNewRoute =
  PrivateSettingsGeneralCustomersNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PrivateSettingsGeneralCustomersListRoute,
  } as any)

const PrivateProjectProjectIdIssuesRequestRoute =
  PrivateProjectProjectIdIssuesRequestImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => PrivateProjectProjectIdIssuesRoute,
  } as any)

const PrivateProjectProjectIdIssuesPriceRoute =
  PrivateProjectProjectIdIssuesPriceImport.update({
    id: '/price',
    path: '/price',
    getParentRoute: () => PrivateProjectProjectIdIssuesRoute,
  } as any)

const PrivateProjectProjectIdIssuesMeRoute =
  PrivateProjectProjectIdIssuesMeImport.update({
    id: '/me',
    path: '/me',
    getParentRoute: () => PrivateProjectProjectIdIssuesRoute,
  } as any)

const PrivateProjectProjectIdContractMonitoringRoute =
  PrivateProjectProjectIdContractMonitoringImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => PrivateProjectProjectIdContractRoute,
  } as any)

const PrivateProjectProjectIdContractInputRoute =
  PrivateProjectProjectIdContractInputImport.update({
    id: '/input',
    path: '/input',
    getParentRoute: () => PrivateProjectProjectIdContractRoute,
  } as any)

const PrivateProjectProjectIdIssuesRequestIndexRoute =
  PrivateProjectProjectIdIssuesRequestIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProjectProjectIdIssuesRequestRoute,
  } as any)

const PrivateProjectProjectIdIssuesPriceIndexRoute =
  PrivateProjectProjectIdIssuesPriceIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProjectProjectIdIssuesPriceRoute,
  } as any)

const PrivateProjectProjectIdIssuesMeIndexRoute =
  PrivateProjectProjectIdIssuesMeIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateProjectProjectIdIssuesMeRoute,
  } as any)

const PrivateSettingsOperationProcessEditRoute =
  PrivateSettingsOperationProcessEditImport.update({
    id: '/$processId/edit',
    path: '/$processId/edit',
    getParentRoute: () => PrivateSettingsOperationProcessListRoute,
  } as any)

const PrivateSettingsOperationObjectsEditRoute =
  PrivateSettingsOperationObjectsEditImport.update({
    id: '/$objectId/edit',
    path: '/$objectId/edit',
    getParentRoute: () => PrivateSettingsOperationObjectsListRoute,
  } as any)

const PrivateSettingsGeneralSuppliersEditRoute =
  PrivateSettingsGeneralSuppliersEditImport.update({
    id: '/$supplierId/edit',
    path: '/$supplierId/edit',
    getParentRoute: () => PrivateSettingsGeneralSuppliersListRoute,
  } as any)

const PrivateSettingsGeneralMaterialsEditRoute =
  PrivateSettingsGeneralMaterialsEditImport.update({
    id: '/$materialId/edit',
    path: '/$materialId/edit',
    getParentRoute: () => PrivateSettingsGeneralMaterialsListRoute,
  } as any)

const PrivateSettingsGeneralEmployeesEditRoute =
  PrivateSettingsGeneralEmployeesEditImport.update({
    id: '/$employeeId/edit',
    path: '/$employeeId/edit',
    getParentRoute: () => PrivateSettingsGeneralEmployeesListRoute,
  } as any)

const PrivateSettingsGeneralDepartmentsEditRoute =
  PrivateSettingsGeneralDepartmentsEditImport.update({
    id: '/$departmentId/edit',
    path: '/$departmentId/edit',
    getParentRoute: () => PrivateSettingsGeneralDepartmentsListRoute,
  } as any)

const PrivateSettingsGeneralCustomersEditRoute =
  PrivateSettingsGeneralCustomersEditImport.update({
    id: '/$customerId/edit',
    path: '/$customerId/edit',
    getParentRoute: () => PrivateSettingsGeneralCustomersListRoute,
  } as any)

const PrivateProjectProjectIdIssuesRequestIssueIdRoute =
  PrivateProjectProjectIdIssuesRequestIssueIdImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => PrivateProjectProjectIdIssuesRequestRoute,
  } as any)

const PrivateProjectProjectIdIssuesPriceIssueIdRoute =
  PrivateProjectProjectIdIssuesPriceIssueIdImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => PrivateProjectProjectIdIssuesPriceRoute,
  } as any)

const PrivateProjectProjectIdIssuesMeIssueIdRoute =
  PrivateProjectProjectIdIssuesMeIssueIdImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => PrivateProjectProjectIdIssuesMeRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_private/home': {
      id: '/_private/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PrivateHomeImport
      parentRoute: typeof PrivateImport
    }
    '/_private/messenger': {
      id: '/_private/messenger'
      path: '/messenger'
      fullPath: '/messenger'
      preLoaderRoute: typeof PrivateMessengerImport
      parentRoute: typeof PrivateImport
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileImport
      parentRoute: typeof PrivateImport
    }
    '/_private/project': {
      id: '/_private/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof PrivateProjectImport
      parentRoute: typeof PrivateImport
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsImport
      parentRoute: typeof PrivateImport
    }
    '/_private/project/$projectId': {
      id: '/_private/project/$projectId'
      path: '/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof PrivateProjectProjectIdImport
      parentRoute: typeof PrivateProjectImport
    }
    '/_private/settings/general': {
      id: '/_private/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof PrivateSettingsGeneralImport
      parentRoute: typeof PrivateSettingsImport
    }
    '/_private/settings/operation': {
      id: '/_private/settings/operation'
      path: '/operation'
      fullPath: '/settings/operation'
      preLoaderRoute: typeof PrivateSettingsOperationImport
      parentRoute: typeof PrivateSettingsImport
    }
    '/_private/project/': {
      id: '/_private/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof PrivateProjectIndexImport
      parentRoute: typeof PrivateProjectImport
    }
    '/_private/settings/': {
      id: '/_private/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof PrivateSettingsIndexImport
      parentRoute: typeof PrivateSettingsImport
    }
    '/_private/project/$projectId/contract': {
      id: '/_private/project/$projectId/contract'
      path: '/contract'
      fullPath: '/project/$projectId/contract'
      preLoaderRoute: typeof PrivateProjectProjectIdContractImport
      parentRoute: typeof PrivateProjectProjectIdImport
    }
    '/_private/project/$projectId/issues': {
      id: '/_private/project/$projectId/issues'
      path: '/issues'
      fullPath: '/project/$projectId/issues'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesImport
      parentRoute: typeof PrivateProjectProjectIdImport
    }
    '/_private/project/$projectId/settings': {
      id: '/_private/project/$projectId/settings'
      path: '/settings'
      fullPath: '/project/$projectId/settings'
      preLoaderRoute: typeof PrivateProjectProjectIdSettingsImport
      parentRoute: typeof PrivateProjectProjectIdImport
    }
    '/_private/settings/general/customers': {
      id: '/_private/settings/general/customers'
      path: '/customers'
      fullPath: '/settings/general/customers'
      preLoaderRoute: typeof PrivateSettingsGeneralCustomersListImport
      parentRoute: typeof PrivateSettingsGeneralImport
    }
    '/_private/settings/general/departments': {
      id: '/_private/settings/general/departments'
      path: '/departments'
      fullPath: '/settings/general/departments'
      preLoaderRoute: typeof PrivateSettingsGeneralDepartmentsListImport
      parentRoute: typeof PrivateSettingsGeneralImport
    }
    '/_private/settings/general/employees': {
      id: '/_private/settings/general/employees'
      path: '/employees'
      fullPath: '/settings/general/employees'
      preLoaderRoute: typeof PrivateSettingsGeneralEmployeesListImport
      parentRoute: typeof PrivateSettingsGeneralImport
    }
    '/_private/settings/general/materials': {
      id: '/_private/settings/general/materials'
      path: '/materials'
      fullPath: '/settings/general/materials'
      preLoaderRoute: typeof PrivateSettingsGeneralMaterialsListImport
      parentRoute: typeof PrivateSettingsGeneralImport
    }
    '/_private/settings/general/suppliers': {
      id: '/_private/settings/general/suppliers'
      path: '/suppliers'
      fullPath: '/settings/general/suppliers'
      preLoaderRoute: typeof PrivateSettingsGeneralSuppliersListImport
      parentRoute: typeof PrivateSettingsGeneralImport
    }
    '/_private/settings/operation/objects': {
      id: '/_private/settings/operation/objects'
      path: '/objects'
      fullPath: '/settings/operation/objects'
      preLoaderRoute: typeof PrivateSettingsOperationObjectsListImport
      parentRoute: typeof PrivateSettingsOperationImport
    }
    '/_private/settings/operation/process': {
      id: '/_private/settings/operation/process'
      path: '/process'
      fullPath: '/settings/operation/process'
      preLoaderRoute: typeof PrivateSettingsOperationProcessListImport
      parentRoute: typeof PrivateSettingsOperationImport
    }
    '/_private/project/$projectId/': {
      id: '/_private/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof PrivateProjectProjectIdIndexImport
      parentRoute: typeof PrivateProjectProjectIdImport
    }
    '/_private/settings/general/': {
      id: '/_private/settings/general/'
      path: '/'
      fullPath: '/settings/general/'
      preLoaderRoute: typeof PrivateSettingsGeneralIndexImport
      parentRoute: typeof PrivateSettingsGeneralImport
    }
    '/_private/settings/operation/': {
      id: '/_private/settings/operation/'
      path: '/'
      fullPath: '/settings/operation/'
      preLoaderRoute: typeof PrivateSettingsOperationIndexImport
      parentRoute: typeof PrivateSettingsOperationImport
    }
    '/_private/project/$projectId/contract/input': {
      id: '/_private/project/$projectId/contract/input'
      path: '/input'
      fullPath: '/project/$projectId/contract/input'
      preLoaderRoute: typeof PrivateProjectProjectIdContractInputImport
      parentRoute: typeof PrivateProjectProjectIdContractImport
    }
    '/_private/project/$projectId/contract/monitoring': {
      id: '/_private/project/$projectId/contract/monitoring'
      path: '/monitoring'
      fullPath: '/project/$projectId/contract/monitoring'
      preLoaderRoute: typeof PrivateProjectProjectIdContractMonitoringImport
      parentRoute: typeof PrivateProjectProjectIdContractImport
    }
    '/_private/project/$projectId/issues/me': {
      id: '/_private/project/$projectId/issues/me'
      path: '/me'
      fullPath: '/project/$projectId/issues/me'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesMeImport
      parentRoute: typeof PrivateProjectProjectIdIssuesImport
    }
    '/_private/project/$projectId/issues/price': {
      id: '/_private/project/$projectId/issues/price'
      path: '/price'
      fullPath: '/project/$projectId/issues/price'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesPriceImport
      parentRoute: typeof PrivateProjectProjectIdIssuesImport
    }
    '/_private/project/$projectId/issues/request': {
      id: '/_private/project/$projectId/issues/request'
      path: '/request'
      fullPath: '/project/$projectId/issues/request'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesRequestImport
      parentRoute: typeof PrivateProjectProjectIdIssuesImport
    }
    '/_private/settings/general/customers/new': {
      id: '/_private/settings/general/customers/new'
      path: '/new'
      fullPath: '/settings/general/customers/new'
      preLoaderRoute: typeof PrivateSettingsGeneralCustomersNewImport
      parentRoute: typeof PrivateSettingsGeneralCustomersListImport
    }
    '/_private/settings/general/departments/new': {
      id: '/_private/settings/general/departments/new'
      path: '/new'
      fullPath: '/settings/general/departments/new'
      preLoaderRoute: typeof PrivateSettingsGeneralDepartmentsNewImport
      parentRoute: typeof PrivateSettingsGeneralDepartmentsListImport
    }
    '/_private/settings/general/employees/new': {
      id: '/_private/settings/general/employees/new'
      path: '/new'
      fullPath: '/settings/general/employees/new'
      preLoaderRoute: typeof PrivateSettingsGeneralEmployeesNewImport
      parentRoute: typeof PrivateSettingsGeneralEmployeesListImport
    }
    '/_private/settings/general/materials/new': {
      id: '/_private/settings/general/materials/new'
      path: '/new'
      fullPath: '/settings/general/materials/new'
      preLoaderRoute: typeof PrivateSettingsGeneralMaterialsNewImport
      parentRoute: typeof PrivateSettingsGeneralMaterialsListImport
    }
    '/_private/settings/general/suppliers/new': {
      id: '/_private/settings/general/suppliers/new'
      path: '/new'
      fullPath: '/settings/general/suppliers/new'
      preLoaderRoute: typeof PrivateSettingsGeneralSuppliersNewImport
      parentRoute: typeof PrivateSettingsGeneralSuppliersListImport
    }
    '/_private/settings/operation/objects/new': {
      id: '/_private/settings/operation/objects/new'
      path: '/new'
      fullPath: '/settings/operation/objects/new'
      preLoaderRoute: typeof PrivateSettingsOperationObjectsNewImport
      parentRoute: typeof PrivateSettingsOperationObjectsListImport
    }
    '/_private/settings/operation/process/new': {
      id: '/_private/settings/operation/process/new'
      path: '/new'
      fullPath: '/settings/operation/process/new'
      preLoaderRoute: typeof PrivateSettingsOperationProcessNewImport
      parentRoute: typeof PrivateSettingsOperationProcessListImport
    }
    '/_private/project/$projectId/contract/': {
      id: '/_private/project/$projectId/contract/'
      path: '/'
      fullPath: '/project/$projectId/contract/'
      preLoaderRoute: typeof PrivateProjectProjectIdContractIndexImport
      parentRoute: typeof PrivateProjectProjectIdContractImport
    }
    '/_private/project/$projectId/issues/': {
      id: '/_private/project/$projectId/issues/'
      path: '/'
      fullPath: '/project/$projectId/issues/'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesIndexImport
      parentRoute: typeof PrivateProjectProjectIdIssuesImport
    }
    '/_private/project/$projectId/issues/me/$issueId': {
      id: '/_private/project/$projectId/issues/me/$issueId'
      path: '/$issueId'
      fullPath: '/project/$projectId/issues/me/$issueId'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesMeIssueIdImport
      parentRoute: typeof PrivateProjectProjectIdIssuesMeImport
    }
    '/_private/project/$projectId/issues/price/$issueId': {
      id: '/_private/project/$projectId/issues/price/$issueId'
      path: '/$issueId'
      fullPath: '/project/$projectId/issues/price/$issueId'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesPriceIssueIdImport
      parentRoute: typeof PrivateProjectProjectIdIssuesPriceImport
    }
    '/_private/project/$projectId/issues/request/$issueId': {
      id: '/_private/project/$projectId/issues/request/$issueId'
      path: '/$issueId'
      fullPath: '/project/$projectId/issues/request/$issueId'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesRequestIssueIdImport
      parentRoute: typeof PrivateProjectProjectIdIssuesRequestImport
    }
    '/_private/settings/general/customers/$customerId/edit': {
      id: '/_private/settings/general/customers/$customerId/edit'
      path: '/$customerId/edit'
      fullPath: '/settings/general/customers/$customerId/edit'
      preLoaderRoute: typeof PrivateSettingsGeneralCustomersEditImport
      parentRoute: typeof PrivateSettingsGeneralCustomersListImport
    }
    '/_private/settings/general/departments/$departmentId/edit': {
      id: '/_private/settings/general/departments/$departmentId/edit'
      path: '/$departmentId/edit'
      fullPath: '/settings/general/departments/$departmentId/edit'
      preLoaderRoute: typeof PrivateSettingsGeneralDepartmentsEditImport
      parentRoute: typeof PrivateSettingsGeneralDepartmentsListImport
    }
    '/_private/settings/general/employees/$employeeId/edit': {
      id: '/_private/settings/general/employees/$employeeId/edit'
      path: '/$employeeId/edit'
      fullPath: '/settings/general/employees/$employeeId/edit'
      preLoaderRoute: typeof PrivateSettingsGeneralEmployeesEditImport
      parentRoute: typeof PrivateSettingsGeneralEmployeesListImport
    }
    '/_private/settings/general/materials/$materialId/edit': {
      id: '/_private/settings/general/materials/$materialId/edit'
      path: '/$materialId/edit'
      fullPath: '/settings/general/materials/$materialId/edit'
      preLoaderRoute: typeof PrivateSettingsGeneralMaterialsEditImport
      parentRoute: typeof PrivateSettingsGeneralMaterialsListImport
    }
    '/_private/settings/general/suppliers/$supplierId/edit': {
      id: '/_private/settings/general/suppliers/$supplierId/edit'
      path: '/$supplierId/edit'
      fullPath: '/settings/general/suppliers/$supplierId/edit'
      preLoaderRoute: typeof PrivateSettingsGeneralSuppliersEditImport
      parentRoute: typeof PrivateSettingsGeneralSuppliersListImport
    }
    '/_private/settings/operation/objects/$objectId/edit': {
      id: '/_private/settings/operation/objects/$objectId/edit'
      path: '/$objectId/edit'
      fullPath: '/settings/operation/objects/$objectId/edit'
      preLoaderRoute: typeof PrivateSettingsOperationObjectsEditImport
      parentRoute: typeof PrivateSettingsOperationObjectsListImport
    }
    '/_private/settings/operation/process/$processId/edit': {
      id: '/_private/settings/operation/process/$processId/edit'
      path: '/$processId/edit'
      fullPath: '/settings/operation/process/$processId/edit'
      preLoaderRoute: typeof PrivateSettingsOperationProcessEditImport
      parentRoute: typeof PrivateSettingsOperationProcessListImport
    }
    '/_private/project/$projectId/issues/me/': {
      id: '/_private/project/$projectId/issues/me/'
      path: '/'
      fullPath: '/project/$projectId/issues/me/'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesMeIndexImport
      parentRoute: typeof PrivateProjectProjectIdIssuesMeImport
    }
    '/_private/project/$projectId/issues/price/': {
      id: '/_private/project/$projectId/issues/price/'
      path: '/'
      fullPath: '/project/$projectId/issues/price/'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesPriceIndexImport
      parentRoute: typeof PrivateProjectProjectIdIssuesPriceImport
    }
    '/_private/project/$projectId/issues/request/': {
      id: '/_private/project/$projectId/issues/request/'
      path: '/'
      fullPath: '/project/$projectId/issues/request/'
      preLoaderRoute: typeof PrivateProjectProjectIdIssuesRequestIndexImport
      parentRoute: typeof PrivateProjectProjectIdIssuesRequestImport
    }
  }
}

// Create and export the route tree

interface PrivateProjectProjectIdContractRouteChildren {
  PrivateProjectProjectIdContractInputRoute: typeof PrivateProjectProjectIdContractInputRoute
  PrivateProjectProjectIdContractMonitoringRoute: typeof PrivateProjectProjectIdContractMonitoringRoute
  PrivateProjectProjectIdContractIndexRoute: typeof PrivateProjectProjectIdContractIndexRoute
}

const PrivateProjectProjectIdContractRouteChildren: PrivateProjectProjectIdContractRouteChildren =
  {
    PrivateProjectProjectIdContractInputRoute:
      PrivateProjectProjectIdContractInputRoute,
    PrivateProjectProjectIdContractMonitoringRoute:
      PrivateProjectProjectIdContractMonitoringRoute,
    PrivateProjectProjectIdContractIndexRoute:
      PrivateProjectProjectIdContractIndexRoute,
  }

const PrivateProjectProjectIdContractRouteWithChildren =
  PrivateProjectProjectIdContractRoute._addFileChildren(
    PrivateProjectProjectIdContractRouteChildren,
  )

interface PrivateProjectProjectIdIssuesMeRouteChildren {
  PrivateProjectProjectIdIssuesMeIssueIdRoute: typeof PrivateProjectProjectIdIssuesMeIssueIdRoute
  PrivateProjectProjectIdIssuesMeIndexRoute: typeof PrivateProjectProjectIdIssuesMeIndexRoute
}

const PrivateProjectProjectIdIssuesMeRouteChildren: PrivateProjectProjectIdIssuesMeRouteChildren =
  {
    PrivateProjectProjectIdIssuesMeIssueIdRoute:
      PrivateProjectProjectIdIssuesMeIssueIdRoute,
    PrivateProjectProjectIdIssuesMeIndexRoute:
      PrivateProjectProjectIdIssuesMeIndexRoute,
  }

const PrivateProjectProjectIdIssuesMeRouteWithChildren =
  PrivateProjectProjectIdIssuesMeRoute._addFileChildren(
    PrivateProjectProjectIdIssuesMeRouteChildren,
  )

interface PrivateProjectProjectIdIssuesPriceRouteChildren {
  PrivateProjectProjectIdIssuesPriceIssueIdRoute: typeof PrivateProjectProjectIdIssuesPriceIssueIdRoute
  PrivateProjectProjectIdIssuesPriceIndexRoute: typeof PrivateProjectProjectIdIssuesPriceIndexRoute
}

const PrivateProjectProjectIdIssuesPriceRouteChildren: PrivateProjectProjectIdIssuesPriceRouteChildren =
  {
    PrivateProjectProjectIdIssuesPriceIssueIdRoute:
      PrivateProjectProjectIdIssuesPriceIssueIdRoute,
    PrivateProjectProjectIdIssuesPriceIndexRoute:
      PrivateProjectProjectIdIssuesPriceIndexRoute,
  }

const PrivateProjectProjectIdIssuesPriceRouteWithChildren =
  PrivateProjectProjectIdIssuesPriceRoute._addFileChildren(
    PrivateProjectProjectIdIssuesPriceRouteChildren,
  )

interface PrivateProjectProjectIdIssuesRequestRouteChildren {
  PrivateProjectProjectIdIssuesRequestIssueIdRoute: typeof PrivateProjectProjectIdIssuesRequestIssueIdRoute
  PrivateProjectProjectIdIssuesRequestIndexRoute: typeof PrivateProjectProjectIdIssuesRequestIndexRoute
}

const PrivateProjectProjectIdIssuesRequestRouteChildren: PrivateProjectProjectIdIssuesRequestRouteChildren =
  {
    PrivateProjectProjectIdIssuesRequestIssueIdRoute:
      PrivateProjectProjectIdIssuesRequestIssueIdRoute,
    PrivateProjectProjectIdIssuesRequestIndexRoute:
      PrivateProjectProjectIdIssuesRequestIndexRoute,
  }

const PrivateProjectProjectIdIssuesRequestRouteWithChildren =
  PrivateProjectProjectIdIssuesRequestRoute._addFileChildren(
    PrivateProjectProjectIdIssuesRequestRouteChildren,
  )

interface PrivateProjectProjectIdIssuesRouteChildren {
  PrivateProjectProjectIdIssuesMeRoute: typeof PrivateProjectProjectIdIssuesMeRouteWithChildren
  PrivateProjectProjectIdIssuesPriceRoute: typeof PrivateProjectProjectIdIssuesPriceRouteWithChildren
  PrivateProjectProjectIdIssuesRequestRoute: typeof PrivateProjectProjectIdIssuesRequestRouteWithChildren
  PrivateProjectProjectIdIssuesIndexRoute: typeof PrivateProjectProjectIdIssuesIndexRoute
}

const PrivateProjectProjectIdIssuesRouteChildren: PrivateProjectProjectIdIssuesRouteChildren =
  {
    PrivateProjectProjectIdIssuesMeRoute:
      PrivateProjectProjectIdIssuesMeRouteWithChildren,
    PrivateProjectProjectIdIssuesPriceRoute:
      PrivateProjectProjectIdIssuesPriceRouteWithChildren,
    PrivateProjectProjectIdIssuesRequestRoute:
      PrivateProjectProjectIdIssuesRequestRouteWithChildren,
    PrivateProjectProjectIdIssuesIndexRoute:
      PrivateProjectProjectIdIssuesIndexRoute,
  }

const PrivateProjectProjectIdIssuesRouteWithChildren =
  PrivateProjectProjectIdIssuesRoute._addFileChildren(
    PrivateProjectProjectIdIssuesRouteChildren,
  )

interface PrivateProjectProjectIdRouteChildren {
  PrivateProjectProjectIdContractRoute: typeof PrivateProjectProjectIdContractRouteWithChildren
  PrivateProjectProjectIdIssuesRoute: typeof PrivateProjectProjectIdIssuesRouteWithChildren
  PrivateProjectProjectIdSettingsRoute: typeof PrivateProjectProjectIdSettingsRoute
  PrivateProjectProjectIdIndexRoute: typeof PrivateProjectProjectIdIndexRoute
}

const PrivateProjectProjectIdRouteChildren: PrivateProjectProjectIdRouteChildren =
  {
    PrivateProjectProjectIdContractRoute:
      PrivateProjectProjectIdContractRouteWithChildren,
    PrivateProjectProjectIdIssuesRoute:
      PrivateProjectProjectIdIssuesRouteWithChildren,
    PrivateProjectProjectIdSettingsRoute: PrivateProjectProjectIdSettingsRoute,
    PrivateProjectProjectIdIndexRoute: PrivateProjectProjectIdIndexRoute,
  }

const PrivateProjectProjectIdRouteWithChildren =
  PrivateProjectProjectIdRoute._addFileChildren(
    PrivateProjectProjectIdRouteChildren,
  )

interface PrivateProjectRouteChildren {
  PrivateProjectProjectIdRoute: typeof PrivateProjectProjectIdRouteWithChildren
  PrivateProjectIndexRoute: typeof PrivateProjectIndexRoute
}

const PrivateProjectRouteChildren: PrivateProjectRouteChildren = {
  PrivateProjectProjectIdRoute: PrivateProjectProjectIdRouteWithChildren,
  PrivateProjectIndexRoute: PrivateProjectIndexRoute,
}

const PrivateProjectRouteWithChildren = PrivateProjectRoute._addFileChildren(
  PrivateProjectRouteChildren,
)

interface PrivateSettingsGeneralCustomersListRouteChildren {
  PrivateSettingsGeneralCustomersNewRoute: typeof PrivateSettingsGeneralCustomersNewRoute
  PrivateSettingsGeneralCustomersEditRoute: typeof PrivateSettingsGeneralCustomersEditRoute
}

const PrivateSettingsGeneralCustomersListRouteChildren: PrivateSettingsGeneralCustomersListRouteChildren =
  {
    PrivateSettingsGeneralCustomersNewRoute:
      PrivateSettingsGeneralCustomersNewRoute,
    PrivateSettingsGeneralCustomersEditRoute:
      PrivateSettingsGeneralCustomersEditRoute,
  }

const PrivateSettingsGeneralCustomersListRouteWithChildren =
  PrivateSettingsGeneralCustomersListRoute._addFileChildren(
    PrivateSettingsGeneralCustomersListRouteChildren,
  )

interface PrivateSettingsGeneralDepartmentsListRouteChildren {
  PrivateSettingsGeneralDepartmentsNewRoute: typeof PrivateSettingsGeneralDepartmentsNewRoute
  PrivateSettingsGeneralDepartmentsEditRoute: typeof PrivateSettingsGeneralDepartmentsEditRoute
}

const PrivateSettingsGeneralDepartmentsListRouteChildren: PrivateSettingsGeneralDepartmentsListRouteChildren =
  {
    PrivateSettingsGeneralDepartmentsNewRoute:
      PrivateSettingsGeneralDepartmentsNewRoute,
    PrivateSettingsGeneralDepartmentsEditRoute:
      PrivateSettingsGeneralDepartmentsEditRoute,
  }

const PrivateSettingsGeneralDepartmentsListRouteWithChildren =
  PrivateSettingsGeneralDepartmentsListRoute._addFileChildren(
    PrivateSettingsGeneralDepartmentsListRouteChildren,
  )

interface PrivateSettingsGeneralEmployeesListRouteChildren {
  PrivateSettingsGeneralEmployeesNewRoute: typeof PrivateSettingsGeneralEmployeesNewRoute
  PrivateSettingsGeneralEmployeesEditRoute: typeof PrivateSettingsGeneralEmployeesEditRoute
}

const PrivateSettingsGeneralEmployeesListRouteChildren: PrivateSettingsGeneralEmployeesListRouteChildren =
  {
    PrivateSettingsGeneralEmployeesNewRoute:
      PrivateSettingsGeneralEmployeesNewRoute,
    PrivateSettingsGeneralEmployeesEditRoute:
      PrivateSettingsGeneralEmployeesEditRoute,
  }

const PrivateSettingsGeneralEmployeesListRouteWithChildren =
  PrivateSettingsGeneralEmployeesListRoute._addFileChildren(
    PrivateSettingsGeneralEmployeesListRouteChildren,
  )

interface PrivateSettingsGeneralMaterialsListRouteChildren {
  PrivateSettingsGeneralMaterialsNewRoute: typeof PrivateSettingsGeneralMaterialsNewRoute
  PrivateSettingsGeneralMaterialsEditRoute: typeof PrivateSettingsGeneralMaterialsEditRoute
}

const PrivateSettingsGeneralMaterialsListRouteChildren: PrivateSettingsGeneralMaterialsListRouteChildren =
  {
    PrivateSettingsGeneralMaterialsNewRoute:
      PrivateSettingsGeneralMaterialsNewRoute,
    PrivateSettingsGeneralMaterialsEditRoute:
      PrivateSettingsGeneralMaterialsEditRoute,
  }

const PrivateSettingsGeneralMaterialsListRouteWithChildren =
  PrivateSettingsGeneralMaterialsListRoute._addFileChildren(
    PrivateSettingsGeneralMaterialsListRouteChildren,
  )

interface PrivateSettingsGeneralSuppliersListRouteChildren {
  PrivateSettingsGeneralSuppliersNewRoute: typeof PrivateSettingsGeneralSuppliersNewRoute
  PrivateSettingsGeneralSuppliersEditRoute: typeof PrivateSettingsGeneralSuppliersEditRoute
}

const PrivateSettingsGeneralSuppliersListRouteChildren: PrivateSettingsGeneralSuppliersListRouteChildren =
  {
    PrivateSettingsGeneralSuppliersNewRoute:
      PrivateSettingsGeneralSuppliersNewRoute,
    PrivateSettingsGeneralSuppliersEditRoute:
      PrivateSettingsGeneralSuppliersEditRoute,
  }

const PrivateSettingsGeneralSuppliersListRouteWithChildren =
  PrivateSettingsGeneralSuppliersListRoute._addFileChildren(
    PrivateSettingsGeneralSuppliersListRouteChildren,
  )

interface PrivateSettingsGeneralRouteChildren {
  PrivateSettingsGeneralCustomersListRoute: typeof PrivateSettingsGeneralCustomersListRouteWithChildren
  PrivateSettingsGeneralDepartmentsListRoute: typeof PrivateSettingsGeneralDepartmentsListRouteWithChildren
  PrivateSettingsGeneralEmployeesListRoute: typeof PrivateSettingsGeneralEmployeesListRouteWithChildren
  PrivateSettingsGeneralMaterialsListRoute: typeof PrivateSettingsGeneralMaterialsListRouteWithChildren
  PrivateSettingsGeneralSuppliersListRoute: typeof PrivateSettingsGeneralSuppliersListRouteWithChildren
  PrivateSettingsGeneralIndexRoute: typeof PrivateSettingsGeneralIndexRoute
}

const PrivateSettingsGeneralRouteChildren: PrivateSettingsGeneralRouteChildren =
  {
    PrivateSettingsGeneralCustomersListRoute:
      PrivateSettingsGeneralCustomersListRouteWithChildren,
    PrivateSettingsGeneralDepartmentsListRoute:
      PrivateSettingsGeneralDepartmentsListRouteWithChildren,
    PrivateSettingsGeneralEmployeesListRoute:
      PrivateSettingsGeneralEmployeesListRouteWithChildren,
    PrivateSettingsGeneralMaterialsListRoute:
      PrivateSettingsGeneralMaterialsListRouteWithChildren,
    PrivateSettingsGeneralSuppliersListRoute:
      PrivateSettingsGeneralSuppliersListRouteWithChildren,
    PrivateSettingsGeneralIndexRoute: PrivateSettingsGeneralIndexRoute,
  }

const PrivateSettingsGeneralRouteWithChildren =
  PrivateSettingsGeneralRoute._addFileChildren(
    PrivateSettingsGeneralRouteChildren,
  )

interface PrivateSettingsOperationObjectsListRouteChildren {
  PrivateSettingsOperationObjectsNewRoute: typeof PrivateSettingsOperationObjectsNewRoute
  PrivateSettingsOperationObjectsEditRoute: typeof PrivateSettingsOperationObjectsEditRoute
}

const PrivateSettingsOperationObjectsListRouteChildren: PrivateSettingsOperationObjectsListRouteChildren =
  {
    PrivateSettingsOperationObjectsNewRoute:
      PrivateSettingsOperationObjectsNewRoute,
    PrivateSettingsOperationObjectsEditRoute:
      PrivateSettingsOperationObjectsEditRoute,
  }

const PrivateSettingsOperationObjectsListRouteWithChildren =
  PrivateSettingsOperationObjectsListRoute._addFileChildren(
    PrivateSettingsOperationObjectsListRouteChildren,
  )

interface PrivateSettingsOperationProcessListRouteChildren {
  PrivateSettingsOperationProcessNewRoute: typeof PrivateSettingsOperationProcessNewRoute
  PrivateSettingsOperationProcessEditRoute: typeof PrivateSettingsOperationProcessEditRoute
}

const PrivateSettingsOperationProcessListRouteChildren: PrivateSettingsOperationProcessListRouteChildren =
  {
    PrivateSettingsOperationProcessNewRoute:
      PrivateSettingsOperationProcessNewRoute,
    PrivateSettingsOperationProcessEditRoute:
      PrivateSettingsOperationProcessEditRoute,
  }

const PrivateSettingsOperationProcessListRouteWithChildren =
  PrivateSettingsOperationProcessListRoute._addFileChildren(
    PrivateSettingsOperationProcessListRouteChildren,
  )

interface PrivateSettingsOperationRouteChildren {
  PrivateSettingsOperationObjectsListRoute: typeof PrivateSettingsOperationObjectsListRouteWithChildren
  PrivateSettingsOperationProcessListRoute: typeof PrivateSettingsOperationProcessListRouteWithChildren
  PrivateSettingsOperationIndexRoute: typeof PrivateSettingsOperationIndexRoute
}

const PrivateSettingsOperationRouteChildren: PrivateSettingsOperationRouteChildren =
  {
    PrivateSettingsOperationObjectsListRoute:
      PrivateSettingsOperationObjectsListRouteWithChildren,
    PrivateSettingsOperationProcessListRoute:
      PrivateSettingsOperationProcessListRouteWithChildren,
    PrivateSettingsOperationIndexRoute: PrivateSettingsOperationIndexRoute,
  }

const PrivateSettingsOperationRouteWithChildren =
  PrivateSettingsOperationRoute._addFileChildren(
    PrivateSettingsOperationRouteChildren,
  )

interface PrivateSettingsRouteChildren {
  PrivateSettingsGeneralRoute: typeof PrivateSettingsGeneralRouteWithChildren
  PrivateSettingsOperationRoute: typeof PrivateSettingsOperationRouteWithChildren
  PrivateSettingsIndexRoute: typeof PrivateSettingsIndexRoute
}

const PrivateSettingsRouteChildren: PrivateSettingsRouteChildren = {
  PrivateSettingsGeneralRoute: PrivateSettingsGeneralRouteWithChildren,
  PrivateSettingsOperationRoute: PrivateSettingsOperationRouteWithChildren,
  PrivateSettingsIndexRoute: PrivateSettingsIndexRoute,
}

const PrivateSettingsRouteWithChildren = PrivateSettingsRoute._addFileChildren(
  PrivateSettingsRouteChildren,
)

interface PrivateRouteChildren {
  PrivateHomeRoute: typeof PrivateHomeRoute
  PrivateMessengerRoute: typeof PrivateMessengerRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateProjectRoute: typeof PrivateProjectRouteWithChildren
  PrivateSettingsRoute: typeof PrivateSettingsRouteWithChildren
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateHomeRoute: PrivateHomeRoute,
  PrivateMessengerRoute: PrivateMessengerRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateProjectRoute: PrivateProjectRouteWithChildren,
  PrivateSettingsRoute: PrivateSettingsRouteWithChildren,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof PrivateHomeRoute
  '/messenger': typeof PrivateMessengerRoute
  '/profile': typeof PrivateProfileRoute
  '/project': typeof PrivateProjectRouteWithChildren
  '/settings': typeof PrivateSettingsRouteWithChildren
  '/project/$projectId': typeof PrivateProjectProjectIdRouteWithChildren
  '/settings/general': typeof PrivateSettingsGeneralRouteWithChildren
  '/settings/operation': typeof PrivateSettingsOperationRouteWithChildren
  '/project/': typeof PrivateProjectIndexRoute
  '/settings/': typeof PrivateSettingsIndexRoute
  '/project/$projectId/contract': typeof PrivateProjectProjectIdContractRouteWithChildren
  '/project/$projectId/issues': typeof PrivateProjectProjectIdIssuesRouteWithChildren
  '/project/$projectId/settings': typeof PrivateProjectProjectIdSettingsRoute
  '/settings/general/customers': typeof PrivateSettingsGeneralCustomersListRouteWithChildren
  '/settings/general/departments': typeof PrivateSettingsGeneralDepartmentsListRouteWithChildren
  '/settings/general/employees': typeof PrivateSettingsGeneralEmployeesListRouteWithChildren
  '/settings/general/materials': typeof PrivateSettingsGeneralMaterialsListRouteWithChildren
  '/settings/general/suppliers': typeof PrivateSettingsGeneralSuppliersListRouteWithChildren
  '/settings/operation/objects': typeof PrivateSettingsOperationObjectsListRouteWithChildren
  '/settings/operation/process': typeof PrivateSettingsOperationProcessListRouteWithChildren
  '/project/$projectId/': typeof PrivateProjectProjectIdIndexRoute
  '/settings/general/': typeof PrivateSettingsGeneralIndexRoute
  '/settings/operation/': typeof PrivateSettingsOperationIndexRoute
  '/project/$projectId/contract/input': typeof PrivateProjectProjectIdContractInputRoute
  '/project/$projectId/contract/monitoring': typeof PrivateProjectProjectIdContractMonitoringRoute
  '/project/$projectId/issues/me': typeof PrivateProjectProjectIdIssuesMeRouteWithChildren
  '/project/$projectId/issues/price': typeof PrivateProjectProjectIdIssuesPriceRouteWithChildren
  '/project/$projectId/issues/request': typeof PrivateProjectProjectIdIssuesRequestRouteWithChildren
  '/settings/general/customers/new': typeof PrivateSettingsGeneralCustomersNewRoute
  '/settings/general/departments/new': typeof PrivateSettingsGeneralDepartmentsNewRoute
  '/settings/general/employees/new': typeof PrivateSettingsGeneralEmployeesNewRoute
  '/settings/general/materials/new': typeof PrivateSettingsGeneralMaterialsNewRoute
  '/settings/general/suppliers/new': typeof PrivateSettingsGeneralSuppliersNewRoute
  '/settings/operation/objects/new': typeof PrivateSettingsOperationObjectsNewRoute
  '/settings/operation/process/new': typeof PrivateSettingsOperationProcessNewRoute
  '/project/$projectId/contract/': typeof PrivateProjectProjectIdContractIndexRoute
  '/project/$projectId/issues/': typeof PrivateProjectProjectIdIssuesIndexRoute
  '/project/$projectId/issues/me/$issueId': typeof PrivateProjectProjectIdIssuesMeIssueIdRoute
  '/project/$projectId/issues/price/$issueId': typeof PrivateProjectProjectIdIssuesPriceIssueIdRoute
  '/project/$projectId/issues/request/$issueId': typeof PrivateProjectProjectIdIssuesRequestIssueIdRoute
  '/settings/general/customers/$customerId/edit': typeof PrivateSettingsGeneralCustomersEditRoute
  '/settings/general/departments/$departmentId/edit': typeof PrivateSettingsGeneralDepartmentsEditRoute
  '/settings/general/employees/$employeeId/edit': typeof PrivateSettingsGeneralEmployeesEditRoute
  '/settings/general/materials/$materialId/edit': typeof PrivateSettingsGeneralMaterialsEditRoute
  '/settings/general/suppliers/$supplierId/edit': typeof PrivateSettingsGeneralSuppliersEditRoute
  '/settings/operation/objects/$objectId/edit': typeof PrivateSettingsOperationObjectsEditRoute
  '/settings/operation/process/$processId/edit': typeof PrivateSettingsOperationProcessEditRoute
  '/project/$projectId/issues/me/': typeof PrivateProjectProjectIdIssuesMeIndexRoute
  '/project/$projectId/issues/price/': typeof PrivateProjectProjectIdIssuesPriceIndexRoute
  '/project/$projectId/issues/request/': typeof PrivateProjectProjectIdIssuesRequestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof PrivateHomeRoute
  '/messenger': typeof PrivateMessengerRoute
  '/profile': typeof PrivateProfileRoute
  '/project': typeof PrivateProjectIndexRoute
  '/settings': typeof PrivateSettingsIndexRoute
  '/project/$projectId/settings': typeof PrivateProjectProjectIdSettingsRoute
  '/settings/general/customers': typeof PrivateSettingsGeneralCustomersListRouteWithChildren
  '/settings/general/departments': typeof PrivateSettingsGeneralDepartmentsListRouteWithChildren
  '/settings/general/employees': typeof PrivateSettingsGeneralEmployeesListRouteWithChildren
  '/settings/general/materials': typeof PrivateSettingsGeneralMaterialsListRouteWithChildren
  '/settings/general/suppliers': typeof PrivateSettingsGeneralSuppliersListRouteWithChildren
  '/settings/operation/objects': typeof PrivateSettingsOperationObjectsListRouteWithChildren
  '/settings/operation/process': typeof PrivateSettingsOperationProcessListRouteWithChildren
  '/project/$projectId': typeof PrivateProjectProjectIdIndexRoute
  '/settings/general': typeof PrivateSettingsGeneralIndexRoute
  '/settings/operation': typeof PrivateSettingsOperationIndexRoute
  '/project/$projectId/contract/input': typeof PrivateProjectProjectIdContractInputRoute
  '/project/$projectId/contract/monitoring': typeof PrivateProjectProjectIdContractMonitoringRoute
  '/settings/general/customers/new': typeof PrivateSettingsGeneralCustomersNewRoute
  '/settings/general/departments/new': typeof PrivateSettingsGeneralDepartmentsNewRoute
  '/settings/general/employees/new': typeof PrivateSettingsGeneralEmployeesNewRoute
  '/settings/general/materials/new': typeof PrivateSettingsGeneralMaterialsNewRoute
  '/settings/general/suppliers/new': typeof PrivateSettingsGeneralSuppliersNewRoute
  '/settings/operation/objects/new': typeof PrivateSettingsOperationObjectsNewRoute
  '/settings/operation/process/new': typeof PrivateSettingsOperationProcessNewRoute
  '/project/$projectId/contract': typeof PrivateProjectProjectIdContractIndexRoute
  '/project/$projectId/issues': typeof PrivateProjectProjectIdIssuesIndexRoute
  '/project/$projectId/issues/me/$issueId': typeof PrivateProjectProjectIdIssuesMeIssueIdRoute
  '/project/$projectId/issues/price/$issueId': typeof PrivateProjectProjectIdIssuesPriceIssueIdRoute
  '/project/$projectId/issues/request/$issueId': typeof PrivateProjectProjectIdIssuesRequestIssueIdRoute
  '/settings/general/customers/$customerId/edit': typeof PrivateSettingsGeneralCustomersEditRoute
  '/settings/general/departments/$departmentId/edit': typeof PrivateSettingsGeneralDepartmentsEditRoute
  '/settings/general/employees/$employeeId/edit': typeof PrivateSettingsGeneralEmployeesEditRoute
  '/settings/general/materials/$materialId/edit': typeof PrivateSettingsGeneralMaterialsEditRoute
  '/settings/general/suppliers/$supplierId/edit': typeof PrivateSettingsGeneralSuppliersEditRoute
  '/settings/operation/objects/$objectId/edit': typeof PrivateSettingsOperationObjectsEditRoute
  '/settings/operation/process/$processId/edit': typeof PrivateSettingsOperationProcessEditRoute
  '/project/$projectId/issues/me': typeof PrivateProjectProjectIdIssuesMeIndexRoute
  '/project/$projectId/issues/price': typeof PrivateProjectProjectIdIssuesPriceIndexRoute
  '/project/$projectId/issues/request': typeof PrivateProjectProjectIdIssuesRequestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/_private/home': typeof PrivateHomeRoute
  '/_private/messenger': typeof PrivateMessengerRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/project': typeof PrivateProjectRouteWithChildren
  '/_private/settings': typeof PrivateSettingsRouteWithChildren
  '/_private/project/$projectId': typeof PrivateProjectProjectIdRouteWithChildren
  '/_private/settings/general': typeof PrivateSettingsGeneralRouteWithChildren
  '/_private/settings/operation': typeof PrivateSettingsOperationRouteWithChildren
  '/_private/project/': typeof PrivateProjectIndexRoute
  '/_private/settings/': typeof PrivateSettingsIndexRoute
  '/_private/project/$projectId/contract': typeof PrivateProjectProjectIdContractRouteWithChildren
  '/_private/project/$projectId/issues': typeof PrivateProjectProjectIdIssuesRouteWithChildren
  '/_private/project/$projectId/settings': typeof PrivateProjectProjectIdSettingsRoute
  '/_private/settings/general/customers': typeof PrivateSettingsGeneralCustomersListRouteWithChildren
  '/_private/settings/general/departments': typeof PrivateSettingsGeneralDepartmentsListRouteWithChildren
  '/_private/settings/general/employees': typeof PrivateSettingsGeneralEmployeesListRouteWithChildren
  '/_private/settings/general/materials': typeof PrivateSettingsGeneralMaterialsListRouteWithChildren
  '/_private/settings/general/suppliers': typeof PrivateSettingsGeneralSuppliersListRouteWithChildren
  '/_private/settings/operation/objects': typeof PrivateSettingsOperationObjectsListRouteWithChildren
  '/_private/settings/operation/process': typeof PrivateSettingsOperationProcessListRouteWithChildren
  '/_private/project/$projectId/': typeof PrivateProjectProjectIdIndexRoute
  '/_private/settings/general/': typeof PrivateSettingsGeneralIndexRoute
  '/_private/settings/operation/': typeof PrivateSettingsOperationIndexRoute
  '/_private/project/$projectId/contract/input': typeof PrivateProjectProjectIdContractInputRoute
  '/_private/project/$projectId/contract/monitoring': typeof PrivateProjectProjectIdContractMonitoringRoute
  '/_private/project/$projectId/issues/me': typeof PrivateProjectProjectIdIssuesMeRouteWithChildren
  '/_private/project/$projectId/issues/price': typeof PrivateProjectProjectIdIssuesPriceRouteWithChildren
  '/_private/project/$projectId/issues/request': typeof PrivateProjectProjectIdIssuesRequestRouteWithChildren
  '/_private/settings/general/customers/new': typeof PrivateSettingsGeneralCustomersNewRoute
  '/_private/settings/general/departments/new': typeof PrivateSettingsGeneralDepartmentsNewRoute
  '/_private/settings/general/employees/new': typeof PrivateSettingsGeneralEmployeesNewRoute
  '/_private/settings/general/materials/new': typeof PrivateSettingsGeneralMaterialsNewRoute
  '/_private/settings/general/suppliers/new': typeof PrivateSettingsGeneralSuppliersNewRoute
  '/_private/settings/operation/objects/new': typeof PrivateSettingsOperationObjectsNewRoute
  '/_private/settings/operation/process/new': typeof PrivateSettingsOperationProcessNewRoute
  '/_private/project/$projectId/contract/': typeof PrivateProjectProjectIdContractIndexRoute
  '/_private/project/$projectId/issues/': typeof PrivateProjectProjectIdIssuesIndexRoute
  '/_private/project/$projectId/issues/me/$issueId': typeof PrivateProjectProjectIdIssuesMeIssueIdRoute
  '/_private/project/$projectId/issues/price/$issueId': typeof PrivateProjectProjectIdIssuesPriceIssueIdRoute
  '/_private/project/$projectId/issues/request/$issueId': typeof PrivateProjectProjectIdIssuesRequestIssueIdRoute
  '/_private/settings/general/customers/$customerId/edit': typeof PrivateSettingsGeneralCustomersEditRoute
  '/_private/settings/general/departments/$departmentId/edit': typeof PrivateSettingsGeneralDepartmentsEditRoute
  '/_private/settings/general/employees/$employeeId/edit': typeof PrivateSettingsGeneralEmployeesEditRoute
  '/_private/settings/general/materials/$materialId/edit': typeof PrivateSettingsGeneralMaterialsEditRoute
  '/_private/settings/general/suppliers/$supplierId/edit': typeof PrivateSettingsGeneralSuppliersEditRoute
  '/_private/settings/operation/objects/$objectId/edit': typeof PrivateSettingsOperationObjectsEditRoute
  '/_private/settings/operation/process/$processId/edit': typeof PrivateSettingsOperationProcessEditRoute
  '/_private/project/$projectId/issues/me/': typeof PrivateProjectProjectIdIssuesMeIndexRoute
  '/_private/project/$projectId/issues/price/': typeof PrivateProjectProjectIdIssuesPriceIndexRoute
  '/_private/project/$projectId/issues/request/': typeof PrivateProjectProjectIdIssuesRequestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/messenger'
    | '/profile'
    | '/project'
    | '/settings'
    | '/project/$projectId'
    | '/settings/general'
    | '/settings/operation'
    | '/project/'
    | '/settings/'
    | '/project/$projectId/contract'
    | '/project/$projectId/issues'
    | '/project/$projectId/settings'
    | '/settings/general/customers'
    | '/settings/general/departments'
    | '/settings/general/employees'
    | '/settings/general/materials'
    | '/settings/general/suppliers'
    | '/settings/operation/objects'
    | '/settings/operation/process'
    | '/project/$projectId/'
    | '/settings/general/'
    | '/settings/operation/'
    | '/project/$projectId/contract/input'
    | '/project/$projectId/contract/monitoring'
    | '/project/$projectId/issues/me'
    | '/project/$projectId/issues/price'
    | '/project/$projectId/issues/request'
    | '/settings/general/customers/new'
    | '/settings/general/departments/new'
    | '/settings/general/employees/new'
    | '/settings/general/materials/new'
    | '/settings/general/suppliers/new'
    | '/settings/operation/objects/new'
    | '/settings/operation/process/new'
    | '/project/$projectId/contract/'
    | '/project/$projectId/issues/'
    | '/project/$projectId/issues/me/$issueId'
    | '/project/$projectId/issues/price/$issueId'
    | '/project/$projectId/issues/request/$issueId'
    | '/settings/general/customers/$customerId/edit'
    | '/settings/general/departments/$departmentId/edit'
    | '/settings/general/employees/$employeeId/edit'
    | '/settings/general/materials/$materialId/edit'
    | '/settings/general/suppliers/$supplierId/edit'
    | '/settings/operation/objects/$objectId/edit'
    | '/settings/operation/process/$processId/edit'
    | '/project/$projectId/issues/me/'
    | '/project/$projectId/issues/price/'
    | '/project/$projectId/issues/request/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/messenger'
    | '/profile'
    | '/project'
    | '/settings'
    | '/project/$projectId/settings'
    | '/settings/general/customers'
    | '/settings/general/departments'
    | '/settings/general/employees'
    | '/settings/general/materials'
    | '/settings/general/suppliers'
    | '/settings/operation/objects'
    | '/settings/operation/process'
    | '/project/$projectId'
    | '/settings/general'
    | '/settings/operation'
    | '/project/$projectId/contract/input'
    | '/project/$projectId/contract/monitoring'
    | '/settings/general/customers/new'
    | '/settings/general/departments/new'
    | '/settings/general/employees/new'
    | '/settings/general/materials/new'
    | '/settings/general/suppliers/new'
    | '/settings/operation/objects/new'
    | '/settings/operation/process/new'
    | '/project/$projectId/contract'
    | '/project/$projectId/issues'
    | '/project/$projectId/issues/me/$issueId'
    | '/project/$projectId/issues/price/$issueId'
    | '/project/$projectId/issues/request/$issueId'
    | '/settings/general/customers/$customerId/edit'
    | '/settings/general/departments/$departmentId/edit'
    | '/settings/general/employees/$employeeId/edit'
    | '/settings/general/materials/$materialId/edit'
    | '/settings/general/suppliers/$supplierId/edit'
    | '/settings/operation/objects/$objectId/edit'
    | '/settings/operation/process/$processId/edit'
    | '/project/$projectId/issues/me'
    | '/project/$projectId/issues/price'
    | '/project/$projectId/issues/request'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/login'
    | '/_private/home'
    | '/_private/messenger'
    | '/_private/profile'
    | '/_private/project'
    | '/_private/settings'
    | '/_private/project/$projectId'
    | '/_private/settings/general'
    | '/_private/settings/operation'
    | '/_private/project/'
    | '/_private/settings/'
    | '/_private/project/$projectId/contract'
    | '/_private/project/$projectId/issues'
    | '/_private/project/$projectId/settings'
    | '/_private/settings/general/customers'
    | '/_private/settings/general/departments'
    | '/_private/settings/general/employees'
    | '/_private/settings/general/materials'
    | '/_private/settings/general/suppliers'
    | '/_private/settings/operation/objects'
    | '/_private/settings/operation/process'
    | '/_private/project/$projectId/'
    | '/_private/settings/general/'
    | '/_private/settings/operation/'
    | '/_private/project/$projectId/contract/input'
    | '/_private/project/$projectId/contract/monitoring'
    | '/_private/project/$projectId/issues/me'
    | '/_private/project/$projectId/issues/price'
    | '/_private/project/$projectId/issues/request'
    | '/_private/settings/general/customers/new'
    | '/_private/settings/general/departments/new'
    | '/_private/settings/general/employees/new'
    | '/_private/settings/general/materials/new'
    | '/_private/settings/general/suppliers/new'
    | '/_private/settings/operation/objects/new'
    | '/_private/settings/operation/process/new'
    | '/_private/project/$projectId/contract/'
    | '/_private/project/$projectId/issues/'
    | '/_private/project/$projectId/issues/me/$issueId'
    | '/_private/project/$projectId/issues/price/$issueId'
    | '/_private/project/$projectId/issues/request/$issueId'
    | '/_private/settings/general/customers/$customerId/edit'
    | '/_private/settings/general/departments/$departmentId/edit'
    | '/_private/settings/general/employees/$employeeId/edit'
    | '/_private/settings/general/materials/$materialId/edit'
    | '/_private/settings/general/suppliers/$supplierId/edit'
    | '/_private/settings/operation/objects/$objectId/edit'
    | '/_private/settings/operation/process/$processId/edit'
    | '/_private/project/$projectId/issues/me/'
    | '/_private/project/$projectId/issues/price/'
    | '/_private/project/$projectId/issues/request/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "./root.tsx",
      "children": [
        "/",
        "/_private",
        "/login"
      ]
    },
    "/": {
      "filePath": "./index.tsx"
    },
    "/_private": {
      "filePath": "./private.tsx",
      "children": [
        "/_private/home",
        "/_private/messenger",
        "/_private/profile",
        "/_private/project",
        "/_private/settings"
      ]
    },
    "/login": {
      "filePath": "./login.tsx"
    },
    "/_private/home": {
      "filePath": "./private/home.tsx",
      "parent": "/_private"
    },
    "/_private/messenger": {
      "filePath": "./private/messenger.tsx",
      "parent": "/_private"
    },
    "/_private/profile": {
      "filePath": "./private/profile.tsx",
      "parent": "/_private"
    },
    "/_private/project": {
      "filePath": "./private/project.tsx",
      "parent": "/_private",
      "children": [
        "/_private/project/$projectId",
        "/_private/project/"
      ]
    },
    "/_private/settings": {
      "filePath": "./private/settings.tsx",
      "parent": "/_private",
      "children": [
        "/_private/settings/general",
        "/_private/settings/operation",
        "/_private/settings/"
      ]
    },
    "/_private/project/$projectId": {
      "filePath": "./private/project/$projectId.tsx",
      "parent": "/_private/project",
      "children": [
        "/_private/project/$projectId/contract",
        "/_private/project/$projectId/issues",
        "/_private/project/$projectId/settings",
        "/_private/project/$projectId/"
      ]
    },
    "/_private/settings/general": {
      "filePath": "./private/settings/general.tsx",
      "parent": "/_private/settings",
      "children": [
        "/_private/settings/general/customers",
        "/_private/settings/general/departments",
        "/_private/settings/general/employees",
        "/_private/settings/general/materials",
        "/_private/settings/general/suppliers",
        "/_private/settings/general/"
      ]
    },
    "/_private/settings/operation": {
      "filePath": "./private/settings/operation.tsx",
      "parent": "/_private/settings",
      "children": [
        "/_private/settings/operation/objects",
        "/_private/settings/operation/process",
        "/_private/settings/operation/"
      ]
    },
    "/_private/project/": {
      "filePath": "./private/project/index.tsx",
      "parent": "/_private/project"
    },
    "/_private/settings/": {
      "filePath": "./private/settings/index.tsx",
      "parent": "/_private/settings"
    },
    "/_private/project/$projectId/contract": {
      "filePath": "./private/project/$projectId/contract.tsx",
      "parent": "/_private/project/$projectId",
      "children": [
        "/_private/project/$projectId/contract/input",
        "/_private/project/$projectId/contract/monitoring",
        "/_private/project/$projectId/contract/"
      ]
    },
    "/_private/project/$projectId/issues": {
      "filePath": "./private/project/$projectId/issues.tsx",
      "parent": "/_private/project/$projectId",
      "children": [
        "/_private/project/$projectId/issues/me",
        "/_private/project/$projectId/issues/price",
        "/_private/project/$projectId/issues/request",
        "/_private/project/$projectId/issues/"
      ]
    },
    "/_private/project/$projectId/settings": {
      "filePath": "./private/project/$projectId/settings.tsx",
      "parent": "/_private/project/$projectId"
    },
    "/_private/settings/general/customers": {
      "filePath": "./private/settings/general/customers/list.tsx",
      "parent": "/_private/settings/general",
      "children": [
        "/_private/settings/general/customers/new",
        "/_private/settings/general/customers/$customerId/edit"
      ]
    },
    "/_private/settings/general/departments": {
      "filePath": "./private/settings/general/departments/list.tsx",
      "parent": "/_private/settings/general",
      "children": [
        "/_private/settings/general/departments/new",
        "/_private/settings/general/departments/$departmentId/edit"
      ]
    },
    "/_private/settings/general/employees": {
      "filePath": "./private/settings/general/employees/list.tsx",
      "parent": "/_private/settings/general",
      "children": [
        "/_private/settings/general/employees/new",
        "/_private/settings/general/employees/$employeeId/edit"
      ]
    },
    "/_private/settings/general/materials": {
      "filePath": "./private/settings/general/materials/list.tsx",
      "parent": "/_private/settings/general",
      "children": [
        "/_private/settings/general/materials/new",
        "/_private/settings/general/materials/$materialId/edit"
      ]
    },
    "/_private/settings/general/suppliers": {
      "filePath": "./private/settings/general/suppliers/list.tsx",
      "parent": "/_private/settings/general",
      "children": [
        "/_private/settings/general/suppliers/new",
        "/_private/settings/general/suppliers/$supplierId/edit"
      ]
    },
    "/_private/settings/operation/objects": {
      "filePath": "./private/settings/operation/objects/list.tsx",
      "parent": "/_private/settings/operation",
      "children": [
        "/_private/settings/operation/objects/new",
        "/_private/settings/operation/objects/$objectId/edit"
      ]
    },
    "/_private/settings/operation/process": {
      "filePath": "./private/settings/operation/process/list.tsx",
      "parent": "/_private/settings/operation",
      "children": [
        "/_private/settings/operation/process/new",
        "/_private/settings/operation/process/$processId/edit"
      ]
    },
    "/_private/project/$projectId/": {
      "filePath": "./private/project/$projectId/index.tsx",
      "parent": "/_private/project/$projectId"
    },
    "/_private/settings/general/": {
      "filePath": "./private/settings/general/index.tsx",
      "parent": "/_private/settings/general"
    },
    "/_private/settings/operation/": {
      "filePath": "./private/settings/operation/index.tsx",
      "parent": "/_private/settings/operation"
    },
    "/_private/project/$projectId/contract/input": {
      "filePath": "./private/project/$projectId/contract/input.tsx",
      "parent": "/_private/project/$projectId/contract"
    },
    "/_private/project/$projectId/contract/monitoring": {
      "filePath": "./private/project/$projectId/contract/monitoring.tsx",
      "parent": "/_private/project/$projectId/contract"
    },
    "/_private/project/$projectId/issues/me": {
      "filePath": "./private/project/$projectId/issues/me.tsx",
      "parent": "/_private/project/$projectId/issues",
      "children": [
        "/_private/project/$projectId/issues/me/$issueId",
        "/_private/project/$projectId/issues/me/"
      ]
    },
    "/_private/project/$projectId/issues/price": {
      "filePath": "./private/project/$projectId/issues/price.tsx",
      "parent": "/_private/project/$projectId/issues",
      "children": [
        "/_private/project/$projectId/issues/price/$issueId",
        "/_private/project/$projectId/issues/price/"
      ]
    },
    "/_private/project/$projectId/issues/request": {
      "filePath": "./private/project/$projectId/issues/request.tsx",
      "parent": "/_private/project/$projectId/issues",
      "children": [
        "/_private/project/$projectId/issues/request/$issueId",
        "/_private/project/$projectId/issues/request/"
      ]
    },
    "/_private/settings/general/customers/new": {
      "filePath": "./private/settings/general/customers/new.tsx",
      "parent": "/_private/settings/general/customers"
    },
    "/_private/settings/general/departments/new": {
      "filePath": "./private/settings/general/departments/new.tsx",
      "parent": "/_private/settings/general/departments"
    },
    "/_private/settings/general/employees/new": {
      "filePath": "./private/settings/general/employees/new.tsx",
      "parent": "/_private/settings/general/employees"
    },
    "/_private/settings/general/materials/new": {
      "filePath": "./private/settings/general/materials/new.tsx",
      "parent": "/_private/settings/general/materials"
    },
    "/_private/settings/general/suppliers/new": {
      "filePath": "./private/settings/general/suppliers/new.tsx",
      "parent": "/_private/settings/general/suppliers"
    },
    "/_private/settings/operation/objects/new": {
      "filePath": "./private/settings/operation/objects/new.tsx",
      "parent": "/_private/settings/operation/objects"
    },
    "/_private/settings/operation/process/new": {
      "filePath": "./private/settings/operation/process/new.tsx",
      "parent": "/_private/settings/operation/process"
    },
    "/_private/project/$projectId/contract/": {
      "filePath": "./private/project/$projectId/contract/index.tsx",
      "parent": "/_private/project/$projectId/contract"
    },
    "/_private/project/$projectId/issues/": {
      "filePath": "./private/project/$projectId/issues/index.tsx",
      "parent": "/_private/project/$projectId/issues"
    },
    "/_private/project/$projectId/issues/me/$issueId": {
      "filePath": "./private/project/$projectId/issues/me/$issueId.tsx",
      "parent": "/_private/project/$projectId/issues/me"
    },
    "/_private/project/$projectId/issues/price/$issueId": {
      "filePath": "./private/project/$projectId/issues/price/$issueId.tsx",
      "parent": "/_private/project/$projectId/issues/price"
    },
    "/_private/project/$projectId/issues/request/$issueId": {
      "filePath": "./private/project/$projectId/issues/request/$issueId.tsx",
      "parent": "/_private/project/$projectId/issues/request"
    },
    "/_private/settings/general/customers/$customerId/edit": {
      "filePath": "./private/settings/general/customers/edit.tsx",
      "parent": "/_private/settings/general/customers"
    },
    "/_private/settings/general/departments/$departmentId/edit": {
      "filePath": "./private/settings/general/departments/edit.tsx",
      "parent": "/_private/settings/general/departments"
    },
    "/_private/settings/general/employees/$employeeId/edit": {
      "filePath": "./private/settings/general/employees/edit.tsx",
      "parent": "/_private/settings/general/employees"
    },
    "/_private/settings/general/materials/$materialId/edit": {
      "filePath": "./private/settings/general/materials/edit.tsx",
      "parent": "/_private/settings/general/materials"
    },
    "/_private/settings/general/suppliers/$supplierId/edit": {
      "filePath": "./private/settings/general/suppliers/edit.tsx",
      "parent": "/_private/settings/general/suppliers"
    },
    "/_private/settings/operation/objects/$objectId/edit": {
      "filePath": "./private/settings/operation/objects/edit.tsx",
      "parent": "/_private/settings/operation/objects"
    },
    "/_private/settings/operation/process/$processId/edit": {
      "filePath": "./private/settings/operation/process/edit.tsx",
      "parent": "/_private/settings/operation/process"
    },
    "/_private/project/$projectId/issues/me/": {
      "filePath": "./private/project/$projectId/issues/me/index.tsx",
      "parent": "/_private/project/$projectId/issues/me"
    },
    "/_private/project/$projectId/issues/price/": {
      "filePath": "./private/project/$projectId/issues/price/index.tsx",
      "parent": "/_private/project/$projectId/issues/price"
    },
    "/_private/project/$projectId/issues/request/": {
      "filePath": "./private/project/$projectId/issues/request/index.tsx",
      "parent": "/_private/project/$projectId/issues/request"
    }
  }
}
ROUTE_MANIFEST_END */
